config/routes.rb
# Rails.application.routes.draw do
  # resources :details
  # resources :people

  # resources :people do
  #   resources :details
  # end

  Rails.application.routes.draw do
    defaults format: :json do
      resources :people, only: [:index, :show, :create, :update, :destroy] do
        resources :details, only: [:index, :show, :create, :update, :destroy]
      end
    end

    root 'home#index'
    
  end
  
#   root 'home#index'
#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
    has_one :detail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_person
  before_action :set_detail, only: [:show, :update, :destroy]

  # GET /people/:person_id/details
  def index
    @details = @person.details
    render json: @details
  end

  # GET /people/:person_id/details/1
  def show
    render json: @detail
  end

  # POST /people/:person_id/details
  def create
    @detail = @person.details.new(detail_params)

    if @detail.save
      render json: @detail, status: :created, location: person_detail_url(@person, @detail)
    else
      render json: @detail.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /people/:person_id/details/1
  def update
    if @detail.update(detail_params)
      render json: @detail
    else
      render json: @detail.errors, status: :unprocessable_entity
    end
  end

  # DELETE /people/:person_id/details/1
  def destroy
    @detail.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:person_id])
    end

    def set_detail
      @detail = @person.details.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def detail_params
      params.require(:detail).permit!
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :update, :destroy]

  # GET /people
  def index
    @people = Person.all
    render json: @people
  end

  # GET /people/1
  def show
    render json: @person
  end

  # POST /people
  def create
    @person = Person.new(person_params)

    if @person.save
      render json: @person, status: :created, location: @person
    else
      render json: @person.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /people/1
  def update
    if @person.update(person_params)
      render json: @person
    else
      render json: @person.errors, status: :unprocessable_entity
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def person_params
      params.require(:person).permit(:name, :info, :title, :age, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/details/_form.html.slim
= form_for @detail do |f|
  - if @detail.errors.any?
    #error_explanation
      h2 = "#{pluralize(@detail.errors.count, "error")} prohibited this detail from being saved:"
      ul
        - @detail.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :person
    = f.text_field :person
  .actions = f.submit

app/views/details/edit.html.slim
h1 Editing detail

== render "form"

=> link_to "Show", @detail
'|
=< link_to "Back", details_path

app/views/details/index.html.slim
h1 Listing details

table
  thead
    tr
      th Person
      th
      th
      th

  tbody
    - @details.each do |detail|
      tr
        td = detail.person
        td = link_to "Show", detail
        td = link_to "Edit", edit_detail_path(detail)
        td = link_to "Destroy", detail, data: {confirm: "Are you sure?"}, method: :delete

br

= link_to "New Detail", new_detail_path

app/views/details/new.html.slim
h1 New detail

== render "form"

= link_to "Back", details_path

app/views/details/show.html.slim
p#notice = notice

p
  strong Person:
  = @detail.person

=> link_to "Edit", edit_detail_path(@detail)
'|
=< link_to "Back", details_path

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Techass</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.slim
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      h2 = "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      ul
        - @person.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :info
    = f.text_area :info
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :age
    = f.number_field :age
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :email
    = f.text_field :email
  .actions = f.submit

app/views/people/edit.html.slim
h1 Editing person

== render "form"

=> link_to "Show", @person
'|
=< link_to "Back", people_path

app/views/people/index.html.slim
h1 Listing people

table
  thead
    tr
      th Name
      th Info
      th Title
      th Age
      th Phone
      th Email
      th
      th
      th

  tbody
    - @people.each do |person|
      tr
        td = person.name
        td = person.info
        td = person.title
        td = person.age
        td = person.phone
        td = person.email
        td = link_to "Show", person
        td = link_to "Edit", edit_person_path(person)
        td = link_to "Destroy", person, data: {confirm: "Are you sure?"}, method: :delete

br

= link_to "New Person", new_person_path

app/views/people/new.html.slim
h1 New person

== render "form"

= link_to "Back", people_path

app/views/people/show.html.slim
p#notice = notice

p
  strong Name:
  = @person.name

p
  strong Info:
  = @person.info

p
  strong Title:
  = @person.title

p
  strong Age:
  = @person.age

p
  strong Phone:
  = @person.phone

p
  strong Email:
  = @person.email

=> link_to "Edit", edit_person_path(@person)
'|
=< link_to "Back", people_path